### PR TITLE
Added an InvokeSharpHound() function to be called by a PS ingestor

### PR DESCRIPTION
**Pull request by lap1nou**
Hello,

This PR just add an InvokeSharpHound() function to be called by a PS ingestor

Linked to this PR: https://github.com/BloodHoundAD/BloodHound/pull/545

### CODE REVIEW

**Comment by rvazarkar** [comment]
Thanks for the PR

**Comment by ddlees** [comment]
recheck

**Comment by ddlees** [comment]
@lap1nou In an attempt to accept contributions the "right" way and be the best stewards we can be to the FOSS community we have recently published a Contributor License Agreement. Would you please consider reading and signing the CLA linked in the comment above? Thank you!

**Comment by lap1nou** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
